#ifndef LTSKKS_INPUT_INCLUDED
#define LTSKKS_INPUT_INCLUDED

#define LTSKKS_SAMPLE_MAIN_TEX(uv) UNITY_SAMPLE_TEX2D(_MainTex, uv)
#define LTSKKS_SAMPLE_TEX(texName, uv) UNITY_SAMPLE_TEX2D_SAMPLER(texName, _MainTex, uv)

UNITY_DECLARE_TEX2D(_MainTex);
float4 _MainTex_ST;
float4 _MainTex_ScrollRotate;
float4 _MainTexHSVG;
float4 _Color;
float _MainGradationStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MainGradationTex);
UNITY_DECLARE_TEX2D_NOSAMPLER(_MainColorAdjustMask);

#if defined(LTSKKS_KKS_HAIR_FRONT_EYE)
float _KKSFrontHairOpacity;
#endif

// KKS body material compatibility. Compiled only by lilToonKKSSkin.
#if defined(LTSKKS_KKS_SKIN)
UNITY_DECLARE_TEX2D(_ColMask);
float4 _ColMask_ST;
float4 _Col0;
float4 _Col1;
float4 _Col2;
float4 _Col3;
// KKS overlay UV sets rely on each texture's own wrap mode outside its authored region.
UNITY_DECLARE_TEX2D(_overtex1);
UNITY_DECLARE_TEX2D(_overtex2);
UNITY_DECLARE_TEX2D(_overtex3);
float4 _overtex1_ST;
float4 _overtex2_ST;
float4 _overtex3_ST;
float4 _overcolor1;
float4 _overcolor2;
float4 _overcolor3;
float _nipsize;
float _nip;
float _nip_specular;
float _tex1mask;
float _alpha_a;
float _alpha_b;
UNITY_DECLARE_TEX2D_NOSAMPLER(_NormalMap);
UNITY_DECLARE_TEX2D_NOSAMPLER(_NormalMapDetail);
float4 _NormalMap_ST;
float4 _NormalMapDetail_ST;
float _NormalMapScale;
float _DetailNormalMapScale;
UNITY_DECLARE_TEX2D_NOSAMPLER(_DetailMask);
float4 _DetailMask_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_EmissionMask);
float4 _EmissionMask_ST;
float _EmissionIntensity;
float _EmissionMaskMode;
UNITY_DECLARE_TEX2D(_KKSFaceGradeMap);
float4 _KKSFaceGradeMap_ST;
float _KKSFaceGradeMode;
float _KKSFaceGradeStrength;
float _KKSFaceGradeOffset;
float _KKSFaceGradeInvert;
float _KKSFaceGradeDirectionOffset;
UNITY_DECLARE_TEX2D(_Texture2);
UNITY_DECLARE_TEX2D_NOSAMPLER(_Texture3);
UNITY_DECLARE_TEX2D_NOSAMPLER(_LiquidPatternTex);
UNITY_DECLARE_TEX2D_NOSAMPLER(_LiquidNormalMap);
UNITY_DECLARE_TEX2D_NOSAMPLER(_liquidmask);
float4 _Texture2_ST;
float4 _Texture3_ST;
float4 _LiquidPatternTex_ST;
float4 _LiquidNormalMap_ST;
float4 _liquidmask_ST;
float4 _LiquidUVTransform;
float _UseLiquidCustomTextures;
float _liquidftop;
float _liquidfbot;
float _liquidbtop;
float _liquidbbot;
float _liquidface;
float4 _LiquidColor;
float _LiquidNormalScale;
float _LiquidSmoothness;
#define LTSKKS_SAMPLE_KKS_SKIN(texName, uv) UNITY_SAMPLE_TEX2D_SAMPLER(texName, _ColMask, uv)
#endif
float _UseParallax;
float _UsePOM;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ParallaxMap);
float _Parallax;
float _ParallaxOffset;
float _TessEdge;
float _TessStrength;
float _TessShrink;
float _TessFactorMax;

float _Invisible;
float _AsUnlit;
float _Cutoff;
float _SubpassCutoff;
float _FlipNormal;
float _ShiftBackfaceUV;
float _BackfaceForceShadow;
float4 _BackfaceColor;
float _VertexLightStrength;
float _LightMinLimit;
float _LightMaxLimit;
float _BeforeExposureLimit;
float _MonochromeLighting;
float _AlphaBoostFA;
float _lilDirectionalLightStrength;
float4 _LightDirectionOverride;
float _AAStrength;
float _UseDither;
UNITY_DECLARE_TEX2D_NOSAMPLER(_DitherTex);
float4 _DitherTex_TexelSize;
float _DitherMaxValue;
sampler3D _DitherMaskLOD;
float _EnvRimBorder;
float _EnvRimBlur;

float _UseMain2ndTex;
float4 _Color2nd;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main2ndTex);
float4 _Main2ndTex_ST;
float _Main2ndTexAngle;
float4 _Main2ndTex_ScrollRotate;
float _Main2ndTex_UVMode;
float _Main2ndTex_Cull;
float4 _Main2ndTexDecalAnimation;
float4 _Main2ndTexDecalSubParam;
float _Main2ndTexIsDecal;
float _Main2ndTexIsLeftOnly;
float _Main2ndTexIsRightOnly;
float _Main2ndTexShouldCopy;
float _Main2ndTexShouldFlipMirror;
float _Main2ndTexShouldFlipCopy;
float _Main2ndTexIsMSDF;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main2ndBlendMask);
float _Main2ndTexBlendMode;
float _Main2ndTexAlphaMode;
float _Main2ndEnableLighting;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main2ndDissolveMask);
float4 _Main2ndDissolveMask_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main2ndDissolveNoiseMask);
float4 _Main2ndDissolveNoiseMask_ST;
float4 _Main2ndDissolveNoiseMask_ScrollRotate;
float _Main2ndDissolveNoiseStrength;
float4 _Main2ndDissolveColor;
float4 _Main2ndDissolveParams;
float4 _Main2ndDissolvePos;
float4 _Main2ndDistanceFade;

float _UseMain3rdTex;
float4 _Color3rd;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main3rdTex);
float4 _Main3rdTex_ST;
float _Main3rdTexAngle;
float4 _Main3rdTex_ScrollRotate;
float _Main3rdTex_UVMode;
float _Main3rdTex_Cull;
float4 _Main3rdTexDecalAnimation;
float4 _Main3rdTexDecalSubParam;
float _Main3rdTexIsDecal;
float _Main3rdTexIsLeftOnly;
float _Main3rdTexIsRightOnly;
float _Main3rdTexShouldCopy;
float _Main3rdTexShouldFlipMirror;
float _Main3rdTexShouldFlipCopy;
float _Main3rdTexIsMSDF;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main3rdBlendMask);
float _Main3rdTexBlendMode;
float _Main3rdTexAlphaMode;
float _Main3rdEnableLighting;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main3rdDissolveMask);
float4 _Main3rdDissolveMask_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Main3rdDissolveNoiseMask);
float4 _Main3rdDissolveNoiseMask_ST;
float4 _Main3rdDissolveNoiseMask_ScrollRotate;
float _Main3rdDissolveNoiseStrength;
float4 _Main3rdDissolveColor;
float4 _Main3rdDissolveParams;
float4 _Main3rdDissolvePos;
float4 _Main3rdDistanceFade;

float _AlphaMaskMode;
#if defined(LTSKKS_KKS_SKIN)
UNITY_DECLARE_TEX2D(_AlphaMask);
#else
UNITY_DECLARE_TEX2D_NOSAMPLER(_AlphaMask);
#endif
float4 _AlphaMask_ST;
float _AlphaMaskScale;
float _AlphaMaskValue;

float _UseBumpMap;
UNITY_DECLARE_TEX2D_NOSAMPLER(_BumpMap);
float4 _BumpMap_ST;
float _BumpScale;
float _UseBump2ndMap;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Bump2ndMap);
float4 _Bump2ndMap_ST;
float _Bump2ndMap_UVMode;
float _Bump2ndScale;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Bump2ndScaleMask);
float4 _Bump2ndScaleMask_ST;

float _UseAnisotropy;
UNITY_DECLARE_TEX2D_NOSAMPLER(_AnisotropyTangentMap);
float4 _AnisotropyTangentMap_ST;
float _AnisotropyScale;
UNITY_DECLARE_TEX2D_NOSAMPLER(_AnisotropyScaleMask);
float4 _AnisotropyScaleMask_ST;
float _AnisotropyTangentWidth;
float _AnisotropyBitangentWidth;
float _AnisotropyShift;
float _AnisotropyShiftNoiseScale;
float _AnisotropySpecularStrength;
float _Anisotropy2ndTangentWidth;
float _Anisotropy2ndBitangentWidth;
float _Anisotropy2ndShift;
float _Anisotropy2ndShiftNoiseScale;
float _Anisotropy2ndSpecularStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_AnisotropyShiftNoiseMask);
float4 _AnisotropyShiftNoiseMask_ST;
float _Anisotropy2Reflection;
float _Anisotropy2MatCap;
float _Anisotropy2MatCap2nd;

float _UseShadow;
float _ShadowStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ShadowStrengthMask);
float _ShadowStrengthMaskLOD;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ShadowBorderMask);
float _ShadowBorderMaskLOD;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ShadowBlurMask);
float _ShadowBlurMaskLOD;
float4 _ShadowAOShift;
float4 _ShadowAOShift2;
float _ShadowPostAO;
float _ShadowColorType;
float4 _ShadowColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ShadowColorTex);
float _ShadowNormalStrength;
float _ShadowBorder;
float _ShadowBlur;
float _ShadowReceive;
float4 _Shadow2ndColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Shadow2ndColorTex);
float _Shadow2ndNormalStrength;
float _Shadow2ndBorder;
float _Shadow2ndBlur;
float _Shadow2ndReceive;
float4 _Shadow3rdColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Shadow3rdColorTex);
float _Shadow3rdNormalStrength;
float _Shadow3rdBorder;
float _Shadow3rdBlur;
float _Shadow3rdReceive;
float4 _ShadowBorderColor;
float _ShadowBorderRange;
float _ShadowMainStrength;
float _ShadowEnvStrength;
float _ShadowMaskType;
float _ShadowFlatBorder;
float _ShadowFlatBlur;

float _UseRimShade;
float4 _RimShadeColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_RimShadeMask);
float _RimShadeNormalStrength;
float _RimShadeBorder;
float _RimShadeBlur;
float _RimShadeFresnelPower;

float _UseBacklight;
float4 _BacklightColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_BacklightColorTex);
float4 _BacklightColorTex_ST;
float _BacklightMainStrength;
float _BacklightNormalStrength;
float _BacklightBorder;
float _BacklightBlur;
float _BacklightDirectivity;
float _BacklightViewStrength;
float _BacklightReceiveShadow;
float _BacklightBackfaceMask;

float _UseReflection;
float _Smoothness;
UNITY_DECLARE_TEX2D_NOSAMPLER(_SmoothnessTex);
float _Metallic;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MetallicGlossMap);
float _Reflectance;
float _GSAAStrength;
float _ApplySpecular;
float _ApplySpecularFA;
float _SpecularToon;
float _SpecularNormalStrength;
float _SpecularBorder;
float _SpecularBlur;
float _ApplyReflection;
float _ReflectionNormalStrength;
float4 _ReflectionColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_ReflectionColorTex);
float _ReflectionApplyTransparency;
samplerCUBE _ReflectionCubeTex;
float4 _ReflectionCubeTex_HDR;
float4 _ReflectionCubeColor;
float _ReflectionCubeOverride;
float _ReflectionCubeEnableLighting;
float _ReflectionBlendMode;

float _UseMatCap;
float4 _MatCapColor;
sampler2D _MatCapTex;
float4 _MatCapTex_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MatCapBlendMask);
float4 _MatCapBlendMask_ST;
float _MatCapBlend;
float _MatCapBlendMode;
float _MatCapPerspective;
float _MatCapZRotCancel;
float _MatCapVRParallaxStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MatCapBumpMap);
float4 _MatCapBumpMap_ST;
float _MatCapBumpScale;
float4 _MatCapBlendUV1;
float _MatCapEnableLighting;
float _MatCapShadowMask;
float _MatCapBackfaceMask;
float _MatCapLod;
float _MatCapApplyTransparency;
float _MatCapNormalStrength;
float _MatCapCustomNormal;
float _MatCapMainStrength;

float _UseMatCap2nd;
float4 _MatCap2ndColor;
sampler2D _MatCap2ndTex;
float4 _MatCap2ndTex_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MatCap2ndBlendMask);
float4 _MatCap2ndBlendMask_ST;
float _MatCap2ndBlend;
float _MatCap2ndBlendMode;
float _MatCap2ndPerspective;
float _MatCap2ndZRotCancel;
float _MatCap2ndVRParallaxStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_MatCap2ndBumpMap);
float4 _MatCap2ndBumpMap_ST;
float _MatCap2ndBumpScale;
float4 _MatCap2ndBlendUV1;
float _MatCap2ndEnableLighting;
float _MatCap2ndShadowMask;
float _MatCap2ndBackfaceMask;
float _MatCap2ndLod;
float _MatCap2ndApplyTransparency;
float _MatCap2ndNormalStrength;
float _MatCap2ndCustomNormal;
float _MatCap2ndMainStrength;

float _UseRim;
float4 _RimColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_RimColorTex);
float4 _RimColorTex_ST;
float _RimMainStrength;
float _RimNormalStrength;
float4 _RimIndirColor;
float _RimBorder;
float _RimBlur;
float _RimFresnelPower;
float _RimShadowMask;
float _RimBackfaceMask;
float _RimVRParallaxStrength;
float _RimApplyTransparency;
float _RimEnableLighting;
float _RimBlendMode;
float _RimDirStrength;
float _RimDirRange;
float _RimIndirRange;
float _RimIndirBorder;
float _RimIndirBlur;

float _UseGlitter;
float _GlitterUVMode;
float4 _GlitterColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_GlitterColorTex);
float4 _GlitterColorTex_ST;
float _GlitterColorTex_UVMode;
float _GlitterMainStrength;
float _GlitterNormalStrength;
float _GlitterScaleRandomize;
float _GlitterApplyShape;
sampler2D _GlitterShapeTex;
float4 _GlitterShapeTex_ST;
float4 _GlitterAtras;
float _GlitterAngleRandomize;
float4 _GlitterParams1;
float4 _GlitterParams2;
float _GlitterPostContrast;
float _GlitterSensitivity;
float _GlitterEnableLighting;
float _GlitterShadowMask;
float _GlitterBackfaceMask;
float _GlitterApplyTransparency;
float _GlitterVRParallaxStrength;

sampler2D _FurNoiseMask;
float4 _FurNoiseMask_ST;
sampler2D _FurMask;
sampler2D _FurLengthMask;
sampler2D _FurVectorTex;
float _FurVectorScale;
float4 _FurVector;
float _VertexColor2FurVector;
float _FurGravity;
float _FurRandomize;
float _FurAO;
float _FurLayerNum;
float _FurRootOffset;
float _FurCutoutLength;
float _FurTouchStrength;
float4 _FurRimColor;
float _FurRimFresnelPower;
float _FurRimAntiLight;
float _FurCull;
float _FurSrcBlend;
float _FurDstBlend;
float _FurSrcBlendAlpha;
float _FurDstBlendAlpha;
float _FurBlendOp;
float _FurBlendOpAlpha;
float _FurSrcBlendFA;
float _FurDstBlendFA;
float _FurSrcBlendAlphaFA;
float _FurDstBlendAlphaFA;
float _FurBlendOpFA;
float _FurBlendOpAlphaFA;
float _FurZClip;
float _FurZWrite;
float _FurZTest;
float _FurStencilRef;
float _FurStencilReadMask;
float _FurStencilWriteMask;
float _FurStencilComp;
float _FurStencilPass;
float _FurStencilFail;
float _FurStencilZFail;
float _FurOffsetFactor;
float _FurOffsetUnits;
float _FurColorMask;
float _FurAlphaToMask;

float _UseEmission;
float4 _EmissionColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_EmissionMap);
float4 _EmissionMap_ST;
float4 _EmissionMap_ScrollRotate;
float _EmissionMainStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_EmissionBlendMask);
float4 _EmissionBlendMask_ST;
float4 _EmissionBlendMask_ScrollRotate;
float _EmissionBlend;
float _EmissionBlendMode;
float _EmissionMap_UVMode;
float4 _EmissionBlink;
float _EmissionUseGrad;
UNITY_DECLARE_TEX2D_NOSAMPLER(_EmissionGradTex);
float _EmissionGradSpeed;
float _EmissionParallaxDepth;
float _EmissionFluorescence;

float _UseEmission2nd;
float4 _Emission2ndColor;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Emission2ndMap);
float4 _Emission2ndMap_ST;
float4 _Emission2ndMap_ScrollRotate;
float _Emission2ndMainStrength;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Emission2ndBlendMask);
float4 _Emission2ndBlendMask_ST;
float4 _Emission2ndBlendMask_ScrollRotate;
float _Emission2ndBlend;
float _Emission2ndBlendMode;
float _Emission2ndMap_UVMode;
float4 _Emission2ndBlink;
float _Emission2ndUseGrad;
UNITY_DECLARE_TEX2D_NOSAMPLER(_Emission2ndGradTex);
float _Emission2ndGradSpeed;
float _Emission2ndParallaxDepth;
float _Emission2ndFluorescence;

UNITY_DECLARE_TEX2D_NOSAMPLER(_DissolveMask);
float4 _DissolveMask_ST;
UNITY_DECLARE_TEX2D_NOSAMPLER(_DissolveNoiseMask);
float4 _DissolveNoiseMask_ST;
float4 _DissolveNoiseMask_ScrollRotate;
float _DissolveNoiseStrength;
float4 _DissolveColor;
float4 _DissolveParams;
float4 _DissolvePos;

float _RefractionStrength;
float _RefractionFresnelPower;
float _RefractionColorFromMain;
float4 _RefractionColor;

float _GemChromaticAberration;
float _GemEnvContrast;
float4 _GemEnvColor;
float _GemParticleLoop;
float4 _GemParticleColor;
float _GemVRParallaxStrength;

float _UseOutline;
float4 _OutlineColor;
sampler2D _OutlineTex;
float4 _OutlineTex_ST;
float4 _OutlineTex_ScrollRotate;
float4 _OutlineTexHSVG;
float4 _OutlineLitColor;
float _OutlineLitApplyTex;
float _OutlineLitScale;
float _OutlineLitOffset;
float _OutlineLitShadowReceive;
float _OutlineWidth;
sampler2D _OutlineWidthMask;
float _OutlineFixWidth;
float _OutlineVertexR2Width;
float _OutlineDeleteMesh;
sampler2D _OutlineVectorTex;
float _OutlineVectorUVMode;
float _OutlineVectorScale;
float _OutlineEnableLighting;
float _OutlineZBias;
float _OutlineDisableInVR;
float _OutlineCull;
float _OutlineSrcBlend;
float _OutlineDstBlend;
float _OutlineSrcBlendAlpha;
float _OutlineDstBlendAlpha;
float _OutlineBlendOp;
float _OutlineBlendOpAlpha;
float _OutlineSrcBlendFA;
float _OutlineDstBlendFA;
float _OutlineSrcBlendAlphaFA;
float _OutlineDstBlendAlphaFA;
float _OutlineBlendOpFA;
float _OutlineBlendOpAlphaFA;
float _OutlineZClip;
float _OutlineZWrite;
float _OutlineZTest;
float _OutlineStencilRef;
float _OutlineStencilReadMask;
float _OutlineStencilWriteMask;
float _OutlineStencilComp;
float _OutlineStencilPass;
float _OutlineStencilFail;
float _OutlineStencilZFail;
float _OutlineOffsetFactor;
float _OutlineOffsetUnits;
float _OutlineColorMask;
float _OutlineAlphaToMask;
float4 _DistanceFadeColor;
float4 _DistanceFade;
float _DistanceFadeMode;
float4 _DistanceFadeRimColor;
float _DistanceFadeRimFresnelPower;

float _Cull;
float _SrcBlend;
float _DstBlend;
float _SrcBlendAlpha;
float _DstBlendAlpha;
float _BlendOp;
float _BlendOpAlpha;
float _SrcBlendFA;
float _DstBlendFA;
float _SrcBlendAlphaFA;
float _DstBlendAlphaFA;
float _BlendOpFA;
float _BlendOpAlphaFA;
float _ZWrite;
float _ZClip;
float _ZTest;
float _StencilRef;
float _StencilReadMask;
float _StencilWriteMask;
float _StencilComp;
float _StencilPass;
float _StencilFail;
float _StencilZFail;
float _OffsetFactor;
float _OffsetUnits;
float _ColorMask;
float _AlphaToMask;
float4 _PreColor;
float _PreOutType;
float _PreCutoff;
float _PreCull;
float _PreSrcBlend;
float _PreDstBlend;
float _PreSrcBlendAlpha;
float _PreDstBlendAlpha;
float _PreBlendOp;
float _PreBlendOpAlpha;
float _PreSrcBlendFA;
float _PreDstBlendFA;
float _PreSrcBlendAlphaFA;
float _PreDstBlendAlphaFA;
float _PreBlendOpFA;
float _PreBlendOpAlphaFA;
float _PreZWrite;
float _PreZClip;
float _PreZTest;
float _PreStencilRef;
float _PreStencilReadMask;
float _PreStencilWriteMask;
float _PreStencilComp;
float _PreStencilPass;
float _PreStencilFail;
float _PreStencilZFail;
float _PreOffsetFactor;
float _PreOffsetUnits;
float _PreColorMask;
float _PreAlphaToMask;
float _lilShadowCasterBias;

#endif
